### ISSUE TITLE
npm start gives me an error

### ISSUE THREAD

**Issue by HipHapLion** [eduncan26/generator-mean2#1]
npm-debug log:
https://gist.github.com/Nomad21/933b8d6d050fe8b1fce3ef5d2cdf2313

just install yeoman and generator-mean2 from the link below and tried to run  using command npm start then gulp build didnt work.
terminal output: https://gist.github.com/Nomad21/3ef24d610046f58ad68374b2d31ded99
https://www.npmjs.com/package/generator-mean2

**Comment by evan-duncan** [comment]
After you run the yeoman generator to bootstrap the application are you installing the node dependencies?

**Comment by HipHapLion** [comment]
Sorry, forgot to mention about that. I have node, mongo and express installed.
node -v6.4
express -v4.13.4
mongodb -v3.2.9
npm -v3.10.6

**Comment by evan-duncan** [comment]
Does gulp start at all when you run `npm start`? I'm seeing something similar, but I'm seeing gulp tasks running before an exception is raised.

**Comment by HipHapLion** [comment]
Yes it does when i use npm start command but gives a different error with gulp. gulp build  gives me similar error as npm start. i have updated the terminal output. It has the complete error output given when any of the above commands is used. [terminal output here](https://gist.github.com/Nomad21/3ef24d610046f58ad68374b2d31ded99)

**Comment by santiim** [comment]
Hi!, I have the same error
"[10:09:04] ReferenceError: ts is not defined  
   at Gulp.gulp.task (/home/nomad/Documents/appWork/sample-mean2/gulpfile.js:26:18)"

Have you found the solution?

**Comment by akelley** [comment]
@santiim 

I was able to get a little further with this by declaring the ts in the gulp file -

```
var ts = require('gulp-typescript');
```

Also had to install gulp-typescript -

```
npm install gulp-typescript typescript
```

Which then gave the the following error -

```
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
```

So modified the .pipe(tsProject()) as it said to - 

```
gulp.task('build:client', ['lint:sass', 'sass'], () => {
    var tsProject = ts.createProject(__dirname + '/public/tsconfig.json');
    return gulp.src(path.join(__dirname + '/public/**/*.ts'))
        .pipe(tsProject())
        .js
        .pipe(gulp.dest(path.resolve('./public')));
});
```

But now just stuck at it not being able to find the js files -

```
[11:10:16] [nodemon] starting `node server/server.js`
module.js:457
    throw err;
    ^

Error: Cannot find module '/Development/mean2/testMean2/server/server.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by rebase-master** [comment]
Facing the same issue.

**Comment by bcrigler** [comment]
Have the same issue as well.  This seems to be a nice barebones MEAN 2 generator as opposed to a lot of the other one's out there that have tons of extra stuff I do not need.

**Comment by evan-duncan** [comment]
I'll take another look at this. I've been sidetracked with work.

**Comment by JSON5995** [comment]
Facing the same issue here. The build is not generating a server.js file or am I missing something. ran npm start

**Comment by fjpalomoc** [comment]
gulp.task('build:client', ['lint:sass', 'sass'], () => {
	var tsProject = ts.createProject(__dirname + '/public/tsconfig.json');
	return tsProject.src()
		.pipe(tsProject())
		.js
		.pipe(gulp.dest(path.resolve('./public')));
});

gulp.task('build:server', ['lint:ts'], () => {
	spawn({
		cmd: 'tsc',
		args: [
		'-p',
		'/server'
		]
 	});
	var tsProject = ts.createProject(__dirname + '/server/tsconfig.json');
	return tsProject.src()
		.pipe(tsProject())
		.js
		.pipe(gulp.dest(path.resolve('./server')));
});

Now:

"C:\Users\Administrator\AppData\Roaming\npm\gulp.cmd" "build:server" "--color"
[06:20:06] Using gulpfile E:\NetBeansProjects\mean2leasure\gulpfile.js
[06:20:06] Starting 'lint:ts'...
[06:20:09] Finished 'lint:ts' after 3.29 s
[06:20:09] Starting 'build:server'...
[06:20:11] TypeScript: 3 semantic errors
[06:20:11] TypeScript: emit succeeded (with errors)
[06:20:11] Finished 'build:server' after 1.97 s
Done.
server\database\mongo.ts(23,33): error TS2339: Property 'connections' does not exist on type 'typeof "mongoose"'.
server\typings\main\ambient\consolidate\index.d.ts(67,85): error TS2304: Cannot find name 'Promise'.
server\typings\main\ambient\consolidate\index.d.ts(73,79): error TS2304: Cannot find name 'Promise'.

I can't find a solution

**Comment by gigouni** [comment]
Did somebody found a suitable solution?
